//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAwesome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.Seats = new HashSet<Seat>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public int RMId { get; set; }
        public string Name { get; set; }
        public byte Taken { get; set; }
    
        public virtual RoomMovie RoomMovie { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
