//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAwesome
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomSeat
    {
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int SeatId { get; set; }
        public int ColNo { get; set; }
        public int RowNo { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
