//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAwesome
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomMovie
    {
        public RoomMovie()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int MovieId { get; set; }
        public System.DateTime DateAndTime { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual Room Room { get; set; }
    }
}
