//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAwesome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.RoomMovies = new HashSet<RoomMovie>();
            this.RoomSeats = new HashSet<RoomSeat>();
        }
    
        public int Id { get; set; }
        public int Cols { get; set; }
        public int Rows { get; set; }
    
        public virtual ICollection<RoomMovie> RoomMovies { get; set; }
        public virtual ICollection<RoomSeat> RoomSeats { get; set; }
    }
}
