//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAwesome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public int ReservationId { get; set; }
        public int DiscountId { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
